a = int(input("Enter number a: "))
b = int(input("Enter number b: "))
print("Addition: ",a+b)
print("Subtraction: ",a-b)
print("Multiplication: ",a*b)
print("Division: ",a/b)
print("Modulo division: ",a%b)
print("Floor division: ",a//b)
print("Exponent: ",a**b)
